name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build spec
        run: |
          mkdir -p out
          curl --retry 2 --fail https://api.csswg.org/bikeshed/ --output out/index.html --header "Accept: text/plain, text/html" -F die-on=fatal -F file=@"index.bs"

      - name: Copy file_server.ts
        run: cp .github/workflows/file_server.ts out/.file_server.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "proposal-common-min-api"
          entrypoint: ".file_server.ts"
          root: out/
